/device/mavros/mavros_node:
  ros__parameters:
    fcu_url: /dev/pixhawk:57600

/device/mavros/mavros:
  ros__parameters:
    plugin_denylist:
    - "*"
    plugin_allowlist:
    - command
    - sys_status
    - imu
    - setpoint_velocity
    - distance_sensor
    - param

    - velocity_position
    - led_control
    - play_tune_v1
    - rc_joy
    - reboot
    - setup
/device/mavros/sys:
  ros__parameters:
    min_voltage: [15.0]

/device/mavros/velocity_position:
  ros__parameters:
    frame_id: "odom"
    tf:
      send: true
      frame_id: "odom"
      child_frame_id: "base_link"
      send_fcu: false

/device/mavros/setpoint_velocity:
  ros__parameters:
    mav_frame: BODY_NED

/device/mavros/distance_sensor:
  ros__parameters:
    config: "{
      bottom_distance_sensor: {subscriber: false, id: 0, orientation: 25, frame_id: bottom_ds, field_of_view: 0.5},
      back_right_distance_sensor: {subscriber: false, id: 1, orientation: 3, frame_id: back_right_ds, field_of_view: 0.5},
      back_left_distance_sensor: {subscriber: false, id: 2, orientation: 5, frame_id: back_left_ds, field_of_view: 0.5},
    }"
